transcription:
  hf_token: your_hugging_face_token
  device: cpu
  compute_type: int8
  batch_size: 16
  model: tiny
  verification_threshold: 0.1
  verification_model_source: speechbrain/spkrec-ecapa-voxceleb
  verification_model_savedir: pretrained_models/spkrec-ecapa-voxceleb

llm:
  model: ollama/llama2
  api_base_url: http://localhost:11434
  api_key: your_llm_api_key_if_needed

captures:
  capture_dir: captures

user:
  name: "Bob"

vad:
  vad_model_savedir: pretrained_models/vad

deepgram:
  api_key: ""
  model: "nova-2"
  language: "en-US"

streaming_transcription:
  provider: "deepgram"

async_transcription:
  provider: "whisper"  
  #provider: "deepgram"

database:
  url: "sqlite:///./db.sqlite3" 

conversation_endpointing:
  timeout_interval: 10
  min_utterances: 2

notification:
  apn_team_id: ""

