transcription:
  hf_token: your_hugging_face_token
  device: cpu
  compute_type: int8
  batch_size: 16
  model: large-v2
  verification_threshold: 0.1
  verification_model_source: speechbrain/spkrec-ecapa-voxceleb
  verification_model_savedir: pretrained_models/spkrec-ecapa-voxceleb

llm:
  model: ollama/llama2
  api_base_url: http://localhost:11434

captures:
  capture_dir: captures

user:
  name: "Bob"